### ISSUE TITLE
Clickhouse errors on transactions with too many records

### ISSUE THREAD

**Issue by mihallis** [sentry-kubernetes/charts#1140]
Hello i bump to errors on few consumers. I have currently about 256 348 606 transactions unable to process because of that error.
 
on `sentry-snuba-transactions-consumer`
```
snuba.clickhouse.errors.ClickhouseWriterError: Too many parts (300). Merges are processing significantly slower than inserts.
```

and on `sentry-snuba-metrics-consumer`
```
snuba.clickhouse.errors.ClickhouseWriterError: Method write is not supported by storage Distributed with more than one shard and no sharding key provided
```

and on `sentry-snuba-consumer`
```
snuba.clickhouse.errors.ClickhouseWriterError: Too large value for FixedString(32): (while read the value of key primary_hash): (at row 1)
```

is there any solution without deleting records?

Found this on chart version 18.0.1.

I performed upgrade to 19.1.1 and to 20.12.2

**Comment by kspyy** [comment]
Hey there, I actually ran into the `Merges are processing significantly slower than inserts` error yesterday - maybe I can try to help you there, here's some background: https://clickhouse.com/docs/knowledgebase/exception-too-many-parts

I'm no clickhouse expert but this is what I did, hope it helps for the first problem at least! 

Also just to be safe, make sure you're not out of space on each of the pod volumes (`df -h` ) check the /var/lib/clickhouse mount 

I'm running an older version of the chart so I had to add this to my configmap temporarily and bounce the clickhouse statefulset so each one pics up the new config.

What I did (listed commands at the bottom)
1. Exec into onto each clickhouse pod (3 in my case) `kubectl exec -it clickhouse-pod-0 bash` 

2. Start the clickhouse client on the pod (clickhouse client -h clickhouse-pod-0) i think that's the command (not using authentication), once you auth, the sql cli has a smiley like (:

3. on the cli run the command from the above linked article: `select count(*) from system.parts where table = '<table_name>' and active == 1`  - now, I noticed the table name from the sentry-snuba-transaction-log where the error was being thrown, that's what you want to replace table name with in the sql statement (I think you can also find it in the clickhouse pod at `/var/log/clickhouse-server/clickhouse.err.log` . For me, the table name being thrown in the error was called "transactions_local), so my query looked like this:

```sql
select count(*) from system.parts where table = 'transactions_local' and active == 1
```

This should be a number exceeding the default 300, which is what your error said. So maybe set it well above depending on volume of messages you see

4. Repeat for each pod to know the value for each one, I think in the transaction consumer log it will show the problematic clickhouse pod name error in the log, but i checked each one to be sure (mine was just over 300 and it throws that, since that number is exceeded on the clickhouse pods, it causes the transaction consumer pod to fail, etc etc )

5. Once you've confirmed, we want to add / override that [parts_to_throw_insert](https://github.com/sentry-kubernetes/charts/blob/develop/clickhouse/values.yaml#L373) into the clickhouse configmap temporarily, to something higher. I set mine to 1000 temporarily because it was going over 400 or what i set it to.

6. Once the cofigmap is saved, I did a rolling restart on the satefulset clickhouse pods, and restarted the other snuba transactio pods once I knew clickhouse ones were up and running (since they consume the transaction ones i believe), then logged back onto my clickhouse pod that had more than the 300 limit, and kept issuing the table query to watch the number eventually coming down

This is what the config map looks like [here](https://github.com/sentry-kubernetes/charts/blob/develop/clickhouse/templates/configmap-config.yaml#L164-L169)

so in my case i set the following value in my clickhouse configmap temporarily:
```xml
        <merge_tree>
                 <parts_to_throw_insert>1000</parts_to_throw_insert>
       </merge_tree>
```
Eventually that number came down and the transaction consumer pod was no longer throwing the problem. I removed the configmap overrides once I was done.

Here are the commands I used in my scenario:

Once in pod, opening clickhouse sql session
```
clickhouse client -h sentry-prod-clickhouse-0  # your pod(s) name
```
Checking existing mergetree settings (used to confirm my config map mergeTree setting was added, didn't want to alter the table manually, this was easier so each pod picked up the config map)
```sql
select * from system.merge_tree_settings where name = 'parts_to_throw_insert'
```

**Comment by mihallis** [comment]
@kspyy hi, thank you. I checked free space, but i have 41% in use.
But space is OK 
`/dev/sdb         30G   12G   18G  41% /var/lib/clickhouse`

I tried upgrade from 20.12.2 to 21.3.2  and that first errors no more presents. (Merges are processing significantly slower than inserts) is not present on latest version 21.3.2. 

But after upgrade consumers works as expected but records in topic is still high. After looking for logs in clickhouse i found
`DB::ErrnoException: Cannot read from file /sys/block/sdg/stat, errno: 19, strerror: No such device`

Other two errors i have are still here.

**Edit:** one of errors 
`snuba.clickhouse.errors.ClickhouseWriterError: Method write is not supported by storage Distributed with more than one shard and no sharding key provided`

could be fixed by this: https://github.com/getsentry/snuba/issues/4897#issuecomment-1861760378
works for me.


Now i have just have 
`snuba.clickhouse.errors.ClickhouseWriterError: Too large value for FixedString(32): (while read the value of key primary_hash): (at row 1)`
