### ISSUE TITLE
Add LDAP support

### ISSUE THREAD

**Issue by arianf** [sentry-kubernetes/charts#21]
Please add ldap support

**Comment by DandyDeveloper** [comment]
I've added OIDC using the older chart, but this essentially requires a dedicate image as you need to add the plugin to the `requirements.yaml`. 

This could probably be built into the chart, but it might be better having a README informing the users to build their own image and reference the plugin in their `sentry.conf.py`

**Comment by gboor** [comment]
I am also interested in LDAP, as well as OIDC and GCS. The problem is indeed that the Sentry image as provided does not have those plugins baked in.

A quick and dirty option I see is to override the command, though that's not possible without modifying the chart and also adds some startup overhead.

It would be really nice to have some way of installing plugins from chart config, but I think that will require modifications to the Sentry docker image too. Best way for now is building a custom docker image, I think.

**Comment by DandyDeveloper** [comment]
@arianf @gboor I don't think we'll every bring this in, because it is inherently supported. 

You need to pass in the attributes as environment varaibles through your `sentry.conf.py` then just add the env params into the container. 

We already support this. We just can't directly have an option that says "add LDAP" because the plugin has to be built with the Sentry image. 

To confirm, you'll need to: 

* Build the image with the relevant plugins you need
* Add params to sentry.conf.py (As env vars)
* Add Environment to the values.

**Comment by arianf** [comment]
Can confirm was able to get this working

**Comment by ErrorPro** [comment]
Also got this working by following the mentioned steps above:
1. Created an [image with ldap](https://hub.docker.com/layers/175573110/venhub/sentry-ldap/21.8.0/images/sha256-34c788a3504341bb075a8cd1b35bfea15aec69a3d8a5883e9eb7300a6120553d?context=repo) based on sentry
2. Changed the `values.yml`(images.sentry.repository) to use the ldap image
3. Edited the `sentry.conf.py` value in the `configmap-sentry.yaml`, example configuration could be found [here](https://github.com/Banno/getsentry-ldap-auth)
4. Install the chart
