### ISSUE TITLE
PVC for Sentry Web component. Why?

### ISSUE THREAD

**Issue by DandyDeveloper** [sentry-kubernetes/charts#45]
Why do we have a PVC for the sentry-web component? This is bad because:

a. Replicas can't be spawned
b. Deletion of these resources can be cumbersome for backend storage provisioners. 

Just want to understand the reasoning behind this? 

I'm not sure if the web component actually has any need for persistence? But I don't know the deeper architectural design of the web component. My impression was that there were no persistent files written to disk.

**Comment by DandyDeveloper** [comment]
@Mokto

**Comment by DandyDeveloper** [comment]
Sorry I've just seen that there are indeed artifacts stored: https://docs.sentry.io/server/filestore/

We'll need to change this to support multiple replicas.

My suggestion is making this a statefulset as well.

**Comment by Mokto** [comment]
Yes, agreed that it's generally better to use another system for persistence (GCS, S3 for example). https://docs.sentry.io/server/filestore/

But some people might want to use the filesystem storage with a ReadWriteMany mode.
We can't really change it because it depends on which provider people use (efs for Amazon, nfs for Google, etc...)

Maybe we could put a note in the readme, or in the values.yaml file explaining that we recommend using GCS or S3.

**Comment by Mokto** [comment]
If you make it a statefulset, then each replica has its own list of files, and sourcemaps don't work anymore.

**Comment by DandyDeveloper** [comment]
@Mokto Does the PVC has `ReadWriteMany`? My replicas were struggling with mounting. 

Looks like we default to `ReadWriteOnce`. Maybe we should update this to Many?

In my case, we're bare metal and host through our own block storage, so I actually would like this working, haha

**Comment by Mokto** [comment]
We could, but most providers don't support ReadWriteMany per default.
You could use that https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner.

Once again, we can change it, but we'll need to be clear on how to allow ReadWriteMany.

**Comment by Mokto** [comment]
I copied the warning from the old chart, I think that's enough.

Let me know if you think we can do more.
