### ISSUE TITLE
Version 15.0.9 sentry-db-check fails due to change version from batch/v1 to batch/v1beta1

### ISSUE THREAD

**Issue by nyambati** [sentry-kubernetes/charts#701]
While upgrading chart to version 15.0.9 from version 5.0.1 I encountered this error. The diff shows that we changed the kind version from `batch/v1` to `batch/v1beta1` was this intended?
```
STDERR:
  Error: UPGRADE FAILED: post-upgrade hooks failed: unable to build kubernetes object for deleting hook sentry/templates/hooks/sentry-db-check.job.yaml: resource mapping not found for name: "sentry-db-check" namespace: "" from "": no matches for kind "Job" in version "batch/v1beta1"
  ensure CRDs are installed first
```

**Comment by yanntoque** [comment]
Thanks ! 

This was not intended, here is a [fix](https://github.com/sentry-kubernetes/charts/pull/704). 

In the PR #700  I changed the batch apiVersion for both job and cronjobs because the batch/v1beta1 is deprecated starting v1.21 of kubernetes and will no longer be used in v1.25 

I haven't taken in account that only cronjobs are affected by this API migration.
